name = "optimaiden"
description = "An OPTIMADE protocol implementation in Ada."
version = "0.1.0-dev"

authors = ["Saulius Gražulis"]
maintainers = ["Saulius Gražulis <grazulis@ibt.lt>"]
maintainers-logins = ["github-username"]
licenses = "LGPL-3.0-or-later"
website = ""
tags = []

[[depends-on]]
json = "^5.0.3"

[[depends-on]]
aws = "^24.0.0"

[[depends-on]]
gnatcoll = "^24.0.0"

[[depends-on]]
utilada = "^2.6.0"
