--  Warning: This file is automatically generated by AYACC.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.
with Filter_AST; use Filter_AST;

package Filter is

    procedure YYParse;

    function Parse (S : String) return Filter_AST.AST_Type;

end Filter;
