--  Warning: This lexical scanner is automatically generated by AFLEX.
--           It is useless to modify it. Change the ".Y" & ".L" files instead.
--  Template: templates/body-lex.adb
with Ada.Text_IO; use Ada.Text_IO;
with filter_lexer_DFA; use filter_lexer_DFA;
with filter_lexer_IO; use filter_lexer_IO;
--# line 1 "filter_lexer.l"
-- Double-quoted string:
--# line 11 "filter_lexer.l"


with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with filter_tokens; use filter_tokens;

package filter_lexer is
  function YYLex return Token;
end;
